apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/System/Volumes/Data/Working/data" #host location
